import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Alex',
      email: '',
      password: bcrypt.hashSync('1234321', 8),
      isAdmin: true,
    },
    {
      name: 'Mike',
      email: '',
      password: bcrypt.hashSync('1234321', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 11111,
      countInStock: 10,
      brand: 'Nike',
      rating: 1.1,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      name: 'Puma slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 2222,
      countInStock: 1,
      brand: 'Nike',
      rating: 2.2,
      numReviews: 2,
      description: 'high quality product',
    },
    {
      name: 'Egg slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 3333,
      countInStock: 0,
      brand: 'Nike',
      rating: 3.3,
      numReviews: 3,
      description: 'high quality product',
    },
    {
      name: 'Adidias slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 4444,
      countInStock: 1009,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 4,
      description: 'high quality product',
    },
    {
      name: 'Eminim slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 5555,
      countInStock: 9898,
      brand: 'Nike',
      rating: 5,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      name: 'Yuma slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 6666,
      countInStock: 6676,
      brand: 'Nike',
      rating: 6.6,
      numReviews: 6,
      description: 'high quality product',
    },
  ],
};

export default data;
